version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: municipal_postgres
    environment:
      POSTGRES_USER: municipal_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: municipal_records
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U municipal_user -d municipal_records"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: municipal_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: